version: "3"
services:

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"

    networks:
      - mern-network
      
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - mern-network
    depends_on:
        - mongo


  mongo:
      image: mongo
      networks:
        - mern-network
      volumes:
        - mongo-data:/data/db

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks: 
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local